### ISSUE TITLE
counts numbers only show up after a non-number key is pressed in normal & visual mode

### ISSUE THREAD

**Issue by let-lc** [NStefan002/screenkey.nvim#16]
### Problem

In normal mode and visual mode, if I want to do `11j` to go down 11 lines, `1 1` will not show up until `j` is pressed, and `1 1 j` will show up at the same time.

Please correct me if the plugin is not intended to capture the counts input, because it captures the number input just fine in insert mode.

### Expected behavior

I'm expecting the behavior to be like: `1` -> `1 1` -> `1 1 j`.

### Neovim version (`nvim -v`)

NVIM v0.9.5

### Terminal name/version

zsh 5.9

**Comment by NStefan002** [comment]
Hi, thanks for reporting. First of all, try using the latest nightly version. As stated in [requirements section](https://github.com/NStefan002/screenkey.nvim?tab=readme-ov-file#%EF%B8%8F-requirements) of the README, screenkey needs a nightly version not older than April 1st. if the issue still exists feel free to comment on this issue and I'll reopen it.
