### ISSUE TITLE
Provide helper function to access recorded keys

### ISSUE THREAD

**Issue by cvigilv** [NStefan002/screenkey.nvim#19]
### Problem

I would like to see the possibility of a small helper function that give acces to the user to use the recorded keys table, in order to make use of this key presses in other places e.g. statusline/tabline component, key logger for stats, etc.

### Expected behavior

I find the implementation of this feature in [tamton-aquib/keys.nvim](https://github.com/tamton-aquib/keys.nvim) a good example.

**Comment by NStefan002** [comment]
Hi! I like your suggestion. Do you mind checking out `statusline-component` branch and giving me your feedback when you have time? Thanks!

Lazy.nvim snippet:
```lua
{
    "NStefan002/screenkey.nvim",
    cmd = "Screenkey",
    branch = "statusline-component",
    opts = {},
}
```

**Comment by NStefan002** [comment]
Thanks for the feedback!

>  I would like to use the statusline component without the floating window of Screenkey. 

Makes sense. I have a few suggestions for this, let me know which one you like the most:
- statusline component is always active, regardless of the Screenkey window
- toggle the statusline component with something like `:Screenkey statusline`
- toggle the statusline component with something like `vim.g.screenkey_statusline = true/false`
- combination of the previous two
- some other method

**Comment by cvigilv** [comment]
I think the best alternative is something like `vim.g.screenkey_statusline = true/false`, since that way the plugin is not running constantly and produce latency issues or other problems

Thanks!

**Comment by NStefan002** [comment]
I added the feature in the [statusline-component](https://github.com/NStefan002/screenkey.nvim/tree/statusline-component) branch along with the usage example in the [how to use section](https://github.com/NStefan002/screenkey.nvim/tree/statusline-component?tab=readme-ov-file#-how-to-use) of the README. Can you give me feedback when you have time?

Thanks for all the help

**Comment by cvigilv** [comment]
works perfect! Thanks!
