### ISSUE TITLE
Leader key mappings are only shown after they are finished 

### ISSUE THREAD

**Issue by SimonBrandner** [NStefan002/screenkey.nvim#29]
### Problem

Let's say I type `<leader>wr` for window resize mode, I only see the whole thing popup after I finish typing `r` while I'd like to see the individual keys pop up one by one.

### Expected behavior

I expect the keys to pop up one by one

### Neovim version (`nvim -v`)

NVIM v0.10.0 Build type: Release LuaJIT 2.1.1693350652

### Terminal name/version

alacritty 0.13.2

**Comment by NStefan002** [comment]
Hi! Currently, this is not a screenkey issue. This is a Neovim limitation (specifically the `vim.on_key` function).
For now, at least, the expected behavior you mentioned is impossible (as far as I know).
