### ISSUE TITLE
add `autostart` option

### ISSUE THREAD

**Issue by GabriWar** [NStefan002/screenkey.nvim#33]
### Problem

would be cool if we had like autostart = true
and it just autostarts because setting autocmds to VimEnter in lazyvim is a pain

### Expected behavior

love the plugin

**Comment by NStefan002** [comment]
Hi! I usually like to leave this type of functionality to users. 

> and it just autostarts because setting autocmds to VimEnter in lazyvim is a pain

I don't know much about lazyvim but I guess that defining autocmds in lazyvim is the same as in any other neovim configuration/distro. 

Do you mind trying this out, if it doesn't work for you I'll add the `autostart` option. Put this code in `plugins/screenkey.lua`:

```lua
return {
    "NStefan002/screenkey.nvim",
    lazy = false,
    version = "*",
    config = function()
        -- require("screenkey").setup() if you want to change some options
        vim.api.nvim_create_autocmd("VimEnter", {
            group = vim.api.nvim_create_augroup("AutostartScreenkey", {}),
            command = "Screenkey toggle",
            desc = "Autostart Screenkey on VimEnter",
        })
    end,
}
```

**Comment by NStefan002** [comment]
Closing this issue because of a long time of inactivity. Feel free to reopen if you still have problems.
