### ISSUE TITLE
Some characters return in bytes

### ISSUE THREAD

**Issue by frvnzj** [NStefan002/screenkey.nvim#37]
### Problem

I'm user with keyboard in spanish, so I use keys like “ñ”, accents or greek alphabet. «Screenkey».set_lines of this characters in bytes.

![imagen](https://github.com/user-attachments/assets/79bef27c-37c4-49f3-910b-8daf0e1d3a04)

### Expected behavior

I hope «Screenkey» can print unicode characters correctly.
![imagen](https://github.com/user-attachments/assets/23bf330c-abd2-4bf8-88f0-c040e298ba4f)

**Comment by frvnzj** [comment]
if set “group_mappings” true, this problem fix, so I close  this issue.

Note: Show leader only works in insert mode.

**Comment by NStefan002** [comment]
Hi, thanks for reporting this! Do you mind checking out the [dev](https://github.com/NStefan002/screenkey.nvim/tree/dev) branch and testing if the latest commit fixed your problem? If you're using lazy.nvim, you can do that via this snippet:

```lua
{
    "NStefan002/screenkey.nvim",
    lazy = false,
    branch = "dev"
}

```

**Comment by frvnzj** [comment]
PERFECT! AWESOME! display unicode :3 thanks!

**Comment by NStefan002** [comment]
I released this fix, you can now use `version = "*"` in your lazy config. Closing.
