### ISSUE TITLE
Error executing  vim.on_key Lua callback: vim/_editor.lua:0: Error executing 'on_key' with ns_ids '28'

### ISSUE THREAD

**Issue by Zeddnyx** [NStefan002/screenkey.nvim#4]
`
Error executing  vim.on_key Lua callback: vim/_editor.lua:0: Error executing 'on_key' with ns_ids '28'
    Messages: ...al/share/nvim/lazy/screenkey.nvim/lua/screenkey/init.lua:268: attempt to get length of local 'typed' (a nil value)
stack traceback:
        [C]: in function 'error'
        vim/_editor.lua: in function <vim/_editor.lua:0>
`

i got that error after type something in keyboard
i just install by followed the `Lazy`
![error-nvim](https://github.com/NStefan002/screenkey.nvim/assets/96564938/1ac34811-6061-4ba9-8d05-9531b02062dd)

os: Arch
terminal: Kitty

**Comment by thohnb** [comment]
Hey. We are in the same boat. Mine is 56.

**Comment by wvffle** [comment]
Here is mine:

![image](https://github.com/NStefan002/screenkey.nvim/assets/13330620/4729a253-f394-467f-a58a-0dde061ad052)

**Comment by NStefan002** [comment]
@Zeddnyx, @thohnb, @wvffle thanks for reporting this. I couldn't find a consistent way to reproduce this, but it should be fixed now. Do you mind testing it ([1.2.1](https://github.com/NStefan002/screenkey.nvim/releases/tag/v1.2.1))?

**Comment by Zeddnyx** [comment]
Sure, I'll try

**Comment by wvffle** [comment]
@NStefan002 thanks for quick reaction! The error does not show up anymore for me but the window does not show any keys being pressed also.

**Comment by NStefan002** [comment]
> ... but the window does not show any keys being pressed also.

@wvffle I don't experience this, do you mind sharing more info?

**Comment by wvffle** [comment]
> do you mind sharing more info?

No matter the mode or the action I do, the Screenkey window stays blank. This may be due to some plugin messing around, as I have a pretty big config. I don't quite have the time to debug this right now, unfortunately.

![image](https://github.com/NStefan002/screenkey.nvim/assets/13330620/6f63bd34-f275-4a88-aa4b-251cdf2bd631)


According to: https://neovim.io/doc/user/lua.html#vim.on_key()

> {typed} is the key(s) before mappings are applied, which may be empty if {key} is produced by non-typed keys.

So I guess, that @Zeddnyx and @thohnb would also have such issue, as the `typed` value was nil for them too. Maybe, if the `typed` is null, you could use `key` as a fallback?

**Comment by Zeddnyx** [comment]
> > do you mind sharing more info?
> 
> No matter the mode or the action I do, the Screenkey window stays blank. This may be due to some plugin messing around, as I have a pretty big config. I don't quite have the time to debug this right now, unfortunately.
> 
> ![image](https://private-user-images.githubusercontent.com/13330620/323410322-6f63bd34-f275-4a88-aa4b-251cdf2bd631.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MDA1OTEsIm5iZiI6MTcxMzQwMDI5MSwicGF0aCI6Ii8xMzMzMDYyMC8zMjM0MTAzMjItNmY2M2JkMzQtZjI3NS00YTg4LWFhNGItMjUxY2RmMmJkNjMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDAwMzEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxNDhiYTVlYzcyODg1Y2MyZjQ0MDBiYzkxYmQ0NDZjYjZmNGIxMWJiNzM5MmMxZDY1MjMxZWY0MTYzNDZiZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.It7F03dZJ7mALw0ai_GVNzDpmom9vd6i4xfxJmrmHOE)
> 
> According to: https://neovim.io/doc/user/lua.html#vim.on_key()
> 
> > {typed} is the key(s) before mappings are applied, which may be empty if {key} is produced by non-typed keys.
> 
> So I guess, that @Zeddnyx and @thohnb would also have such issue, as the `typed` value was nil for them too. Maybe, if the `typed` is null, you could use `key` as a fallback?

yeah i have same issue, yesterday like that, but rn it didint show anything even the error didin't shows up

**Comment by NStefan002** [comment]
I hope it's fixed now. I'm sorry for prolonging this, but I can't test this (I don't get this bug on any machine available to me, or on any terminal I tried). To test this use the following lazy-spec:

```lua
{
    "NStefan002/screenkey.nvim",
    cmd = "Screenkey",
    opts = {},
}
```

Also, please update your nightly version to latest, the new `on_key` was introduce very recently.

**Comment by thohnb** [comment]
Sorry. I was busy recent. After tried. IT work now.
![ảnh](https://github.com/NStefan002/screenkey.nvim/assets/125535323/fc949a97-7c99-4e8c-a0a6-854f20f3e323)

**Comment by Zeddnyx** [comment]
it work for me to, thanks :)

**Comment by NStefan002** [comment]
Thank you guys!
