### ISSUE TITLE
Using lazy.nvim to update plugins gives an error

### ISSUE THREAD

**Issue by try-to-fly** [NStefan002/screenkey.nvim#9]
### Problem

![CleanShot 2024-04-18 at 09 48 00@2x](https://github.com/NStefan002/screenkey.nvim/assets/16008258/112e5e9c-419c-4675-8c2d-386cd8299b40)

Maybe you need to add doc/Screenkey.nvim.txt to gitignore

### Terminal name/version

Kitty

**Comment by NStefan002** [comment]
Oops, classic typo. Thanks for catching this. It should be fixed now, if it keeps happening I'll reopen this issue.
